=== gardener/landscaper/.landscaper/landscaper-service/definition/shoot-configuration.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "github.com/gardener/landscaper/landscaper-service/definitions/shoot-configuration",
  "title": "Landscaper Configuration",
  "description": "Describes the configuration for the shoot cluster deployment.",
  "type": "object",
  "properties": {
    "provider": {
      "$ref": "#definitions/providerConfig"
    },
    "workers": {
      "$ref": "#definitions/workersConfig"
    },
    "region": {
      "type": "string"
    },
    "kubernetes": {
      "$ref": "#definitions/kubernetesConfig"
    },
    "maintenance": {
      "$ref": "#definition/maintenanceConfig"
    }
  },
  "definitions": {
    "providerConfig": {
      "properties": {
        "type": {
          "type": "string",
          "enum": ["gcp"]
        },
        "zone": {
          "type": "string"
        }
      }
    },
    "workersConfig": {
      "properties": {
        "machine": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "image": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "version": {
                  "type": "string"
                }
              }
            }
          }
        },
        "minimum": {
          "type": "integer",
          "format": "int32"
        },
        "maximum": {
          "type": "integer",
          "format": "int32"
        },
        "maxSurge": {
          "type": "integer",
          "format": "int32"
        },
        "maxUnavailable": {
          "type": "integer",
          "format": "int32"
        },
        "volume": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "size": {
              "type": "string"
            }
          }
        }
      }
    },
    "kubernetesConfig": {
      "properties": {
        "version": {
          "type": "string"
        }
      }
    },
    "maintenanceConfig": {
      "properties": {
        "autoUpdate": {
          "type": "object",
          "properties": {
            "kubernetesVersion": {
              "type": "boolean"
            },
            "machineImageVersion": {
              "type": "boolean"
            }
          }
        },
        "timeWindow": {
          "type": "object",
          "properties": {
            "begin": {
              "type": "string"
            },
            "end": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== gardener/landscaper/docs/guided-tour/blueprints/config-file-in-blueprint/blueprint/config.json
{
  "provider": {
    "type": "gcp",
    "zone": "europe-west1-c"
  },
  "region": "europe-west1",
  "workers": {
    "machine": {
      "type": "n1-standard-2",
      "image": {
        "name": "gardenlinux",
        "version": "576.12.0"
      }
    },
    "volume": {
      "type": "pd-standard",
      "size": "50Gi"
    },
    "minimum": 1,
    "maximum": 1,
    "maxSurge": 1,
    "maxUnavailable": 0
  },
  "kubernetes": {
    "version": "1.25"
  },
  "maintenance": {
    "timeWindow": {
      "begin": "050000+0200",
      "end": "060000+0200"
    },
    "autoUpdate": {
      "kubernetesVersion": false,
      "machineImageVersion": false
    }
  }
}
